services:
  - type: web
    name: cineverse-backend
    runtime: python
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Backend.wsgi:application
    healthCheckPath: /