"""
Django settings for Backend project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

import os
from pathlib import Path


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

env_path = BASE_DIR / '.env'

if env_path.exists():
    try:
        from dotenv import load_dotenv
        load_dotenv(env_path)
    except Exception:
        pass

    # Fallback .env loader
    try:
        with open(env_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()

                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    os.environ.setdefault(
                        key.strip(),
                        value.strip()
                    )
    except Exception:
        pass


# ============================================================
# RAZORPAY CONFIGURATION
# ============================================================

RAZORPAY_KEY_ID = os.environ.get(
    'RAZORPAY_KEY_ID',
    ''
)

RAZORPAY_KEY_SECRET = os.environ.get(
    'RAZORPAY_KEY_SECRET',
    ''
)


# ============================================================
# TMDB CONFIGURATION
# ============================================================

TMDB_API_KEY = os.environ.get(
    'TMDB_API_KEY',
    ''
)

TMDB_API_TOKEN = os.environ.get(
    'TMDB_API_TOKEN',
    ''
)


# ============================================================
# GROQ AI CONFIGURATION
# ============================================================

GROQ_API_KEY = os.environ.get(
    'GROQ_API_KEY',
    ''
)


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-only-change-this'
)


# ============================================================
# DEBUG
# ============================================================

DEBUG = os.environ.get(
    'DJANGO_DEBUG',
    'True'
).lower() == 'true'


# ============================================================
# ALLOWED HOSTS
# ============================================================

raw_hosts = os.environ.get(
    'ALLOWED_HOSTS',
    '127.0.0.1,localhost'
)

ALLOWED_HOSTS = [
    host.strip()
    for host in raw_hosts.split(',')
    if host.strip()
]


# ============================================================
# APPLICATION DEFINITION
# ============================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',

    'app',
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = 'Backend.urls'


# ============================================================
# CORS
# ============================================================

raw_cors = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://127.0.0.1:5500,http://localhost:5500'
)

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in raw_cors.split(',')
    if origin.strip()
]


# ============================================================
# CSRF TRUSTED ORIGINS
# ============================================================

raw_csrf = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    ''
)

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in raw_csrf.split(',')
    if origin.strip()
]


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = 'Backend.wsgi.application'


# ============================================================
# DATABASE — AIVEN MYSQL
# ============================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',

        'NAME': os.environ.get(
            'DB_NAME',
            'cineverse'
        ),

        'USER': os.environ.get(
            'DB_USER',
            'avnadmin'
        ),

        'PASSWORD': os.environ.get(
            'DB_PASSWORD',
            ''
        ),

        'HOST': os.environ.get(
            'DB_HOST',
            ''
        ),

        'PORT': os.environ.get(
            'DB_PORT',
            '20407'
        ),

        'OPTIONS': {
            'ssl': {
                'ca': str(
                    BASE_DIR / 'aiven-ca.pem'
                ),
            },
        },
    }
}


# ============================================================
# URL / REQUEST SETTINGS
# ============================================================

APPEND_SLASH = False


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator',
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'


# ============================================================
# WHITENOISE
# ============================================================

MIDDLEWARE.insert(
    1,
    'whitenoise.middleware.WhiteNoiseMiddleware'
)

STATICFILES_STORAGE = (
    'whitenoise.storage.CompressedManifestStaticFilesStorage'
)


# ============================================================
# PRODUCTION SECURITY
# ============================================================

if not DEBUG:

    SECURE_PROXY_SSL_HEADER = (
        'HTTP_X_FORWARDED_PROTO',
        'https'
    )

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True

    SECURE_SSL_REDIRECT = False

    SECURE_CONTENT_TYPE_NOSNIFF = True

    X_FRAME_OPTIONS = 'DENY'